"""create_mvp_tables

Revision ID: 27e092d7c8ce
Revises: 
Create Date: 2026-09-15 23:24:07.669374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e092d7c8ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('cars',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('registration_number', sa.String(length=30), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('transmission', sa.String(length=20), nullable=False),
    sa.Column('seating_capacity', sa.SmallInteger(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('rc_number', sa.String(length=50), nullable=False),
    sa.Column('insurance_policy_number', sa.String(length=50), nullable=False),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weekly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_self_drive_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_driver_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_rate >= 0', name='chk_car_daily_rate_non_negative'),
    sa.CheckConstraint('hourly_rate >= 0', name='chk_car_hourly_rate_non_negative'),
    sa.CheckConstraint('odometer_km >= 0', name='chk_car_odometer_non_negative'),
    sa.CheckConstraint('seating_capacity > 0', name='chk_car_seating_capacity_positive'),
    sa.CheckConstraint('weekly_rate >= 0', name='chk_car_weekly_rate_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_brand'), 'cars', ['brand'], unique=False)
    op.create_index(op.f('ix_cars_city'), 'cars', ['city'], unique=False)
    op.create_index('ix_cars_city_status', 'cars', ['city', 'status'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_index(op.f('ix_cars_owner_id'), 'cars', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cars_registration_number'), 'cars', ['registration_number'], unique=True)
    op.create_index(op.f('ix_cars_status'), 'cars', ['status'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('driving_license_number', sa.String(length=50), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('license_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_license_verified', sa.Boolean(), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_user_id'), 'customer_profiles', ['user_id'], unique=True)
    op.create_table('driver_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry_date', sa.Date(), nullable=False),
    sa.Column('experience_years', sa.SmallInteger(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('duty_status', sa.String(length=20), nullable=False),
    sa.Column('current_city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('experience_years >= 0', name='chk_driver_experience_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_driver_profiles_current_city'), 'driver_profiles', ['current_city'], unique=False)
    op.create_index(op.f('ix_driver_profiles_user_id'), 'driver_profiles', ['user_id'], unique=True)
    op.create_table('owner_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('tax_id_number', sa.String(length=50), nullable=True),
    sa.Column('payout_account_reference', sa.String(length=100), nullable=True),
    sa.Column('payout_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_profiles_user_id'), 'owner_profiles', ['user_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_code', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('booking_type', sa.String(length=20), nullable=False),
    sa.Column('rental_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_location', sa.Text(), nullable=False),
    sa.Column('dropoff_location', sa.Text(), nullable=False),
    sa.Column('start_odometer', sa.Integer(), nullable=True),
    sa.Column('end_odometer', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('driver_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_amount >= 0', name='chk_booking_base_amount_non_negative'),
    sa.CheckConstraint('cancellation_fee >= 0', name='chk_booking_cancellation_fee_non_negative'),
    sa.CheckConstraint('discount_amount >= 0', name='chk_booking_discount_amount_non_negative'),
    sa.CheckConstraint('driver_charge >= 0', name='chk_booking_driver_charge_non_negative'),
    sa.CheckConstraint('end_time > start_time', name='chk_booking_valid_time_window'),
    sa.CheckConstraint('platform_fee >= 0', name='chk_booking_platform_fee_non_negative'),
    sa.CheckConstraint('refund_amount >= 0', name='chk_booking_refund_amount_non_negative'),
    sa.CheckConstraint('security_deposit >= 0', name='chk_booking_security_deposit_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='chk_booking_tax_amount_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='chk_booking_total_amount_non_negative'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_index(op.f('ix_bookings_car_id'), 'bookings', ['car_id'], unique=False)
    op.create_index('ix_bookings_car_window_status', 'bookings', ['car_id', 'start_time', 'end_time', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_driver_id'), 'bookings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_bookings_end_time'), 'bookings', ['end_time'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('car_blackout_periods',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='chk_blackout_valid_time_window'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blackout_car_window', 'car_blackout_periods', ['car_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_car_blackout_periods_car_id'), 'car_blackout_periods', ['car_id'], unique=False)
    op.create_table('car_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_documents_car_id'), 'car_documents', ['car_id'], unique=False)
    op.create_table('car_images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('caption', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_images_car_id'), 'car_images', ['car_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_gateway', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='chk_payment_amount_non_negative'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_reference'), 'payments', ['transaction_reference'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('car_rating', sa.SmallInteger(), nullable=False),
    sa.Column('car_comment', sa.Text(), nullable=True),
    sa.Column('driver_rating', sa.SmallInteger(), nullable=True),
    sa.Column('driver_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('car_rating BETWEEN 1 AND 5', name='chk_review_car_rating_range'),
    sa.CheckConstraint('driver_rating IS NULL OR (driver_rating BETWEEN 1 AND 5)', name='chk_review_driver_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.create_index(op.f('ix_reviews_car_id'), 'reviews', ['car_id'], unique=False)
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reviews_driver_id'), 'reviews', ['driver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_driver_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_car_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payments_transaction_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_car_images_car_id'), table_name='car_images')
    op.drop_table('car_images')
    op.drop_index(op.f('ix_car_documents_car_id'), table_name='car_documents')
    op.drop_table('car_documents')
    op.drop_index(op.f('ix_car_blackout_periods_car_id'), table_name='car_blackout_periods')
    op.drop_index('ix_blackout_car_window', table_name='car_blackout_periods')
    op.drop_table('car_blackout_periods')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_driver_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index('ix_bookings_car_window_status', table_name='bookings')
    op.drop_index(op.f('ix_bookings_car_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_owner_profiles_user_id'), table_name='owner_profiles')
    op.drop_table('owner_profiles')
    op.drop_index(op.f('ix_driver_profiles_user_id'), table_name='driver_profiles')
    op.drop_index(op.f('ix_driver_profiles_current_city'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_customer_profiles_user_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_cars_status'), table_name='cars')
    op.drop_index(op.f('ix_cars_registration_number'), table_name='cars')
    op.drop_index(op.f('ix_cars_owner_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index('ix_cars_city_status', table_name='cars')
    op.drop_index(op.f('ix_cars_city'), table_name='cars')
    op.drop_index(op.f('ix_cars_brand'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
